# this IS the ansible-pull playbook
#
- hosts: all

  tasks:
  - name: Leave evidence in syslog
    syslogger:
      msg: "Hello from ansible"
      priority: "info"
      facility: "daemon"
      log_pid: true

  - name: Leave evidence in file /tmp/ansible-pull.txt
    copy:
      dest: "/tmp/ansible-pull.txt"
      content: |
        ansible-pull evidence
        {{ ansible_date_time.date }}-{{ ansible_date_time.time }}

 # - include: roles/crontab/tasks/main.yml
  - include: roles/crontab
