# this IS the ansible-pull playbook
#
- hosts: all

  tasks:
  - name: Leave evidence in syslog
    syslogger:
      msg: "Hello from ansible"
      priority: "info"
      facility: "daemon"
      log_pid: true

  - name: Leave evidence in a file
    copy:
      dest: "/tmp/ansible-pull.txt"
      content: |
        ansible-pull evidence
        tiger
